### ISSUE TITLE
__kittel_assume and only-loop-conditions option

### ISSUE THREAD

**Issue by jeroenk** [s-falke/llvm2kittel#41]
Naive question: is there a good reason why ```__kittel_assume``` is ignored when the ```only-loop-conditions``` option is passed to llvm2kittel?

**Comment by s-falke** [comment]
The reason is that `__kittel_assume` introduces a constraint and `only-loop-conditions` only allows constraints to be generated from loop guards.  It would of course be possible to add a `only-loop-conditions-and-assumes` option...
