### ISSUE TITLE
Mention `-fno-rtti` to compile in INSTALL

### ISSUE THREAD

**Issue by rgoulter** [s-falke/llvm2kittel#42]
Hi,
When building LLVM with CMake, `LLVM_ENABLE_RTTI` [defaults to 'OFF'](http://llvm.org/docs/CMake.html#llvm-specific-variables).
I'm not sure if the project's root CMakeLists.txt is supposed to consider this or not, but it of course wouldn't compile without adding `-fno-rtti` to `CMAKE_CXX_FLAGS` when building llvm2kittel, so I was a bit confused why it wasn't building.

This had be confused for a bit. Might be worth leaving a note about this in `INSTALL`?

**Comment by s-falke** [comment]
Thanks for reporting.  This seems to be a known bug when building LLVM with CMake, see https://llvm.org/bugs/show_bug.cgi?id=14200  (llvm2kittel depends on on llvm-config --cxxflags to configure its own compiler parameters).

I'll disable rtti the same way we need to enable exceptions.
