### ISSUE TITLE
Bug? Is the option -only-loop-conditions unsound?

### ISSUE THREAD

**Issue by aeflores** [s-falke/llvm2kittel#46]
Hi there,
I found an example in which using the parameter -only-loop-conditions is unsound i.e. the generated file is terminating whereas the original file is not. 
The original code is the following:
~~~~
if (showpass)
	noecho = 0;
    for (;;) {
	fprintf(pgpout, LANG("\nEnter pass phrase: "));
	fflush(pgpout);
	getstring(keystr1, 254 - 1, !noecho);
	if (noecho < 2)
	    break;
	fprintf(pgpout, LANG("\nEnter same pass phrase again: "));
	getstring(keystr2, 254 - 1, !noecho);
	if (strcmp(keystr1, keystr2) == 0)
	    break;
	fprintf(pgpout, LANG("\n\007Error: Pass phrases were different.  Try again."));
	memset(keystr2, 0, sizeof(keystr2));
    }
    ...
~~~~
If showpass is false, noecho is not assigned to 0 and the loop might not terminate. 
If I generate the transition system with the following command:
`./llvm2kittel  buggy_example.bc -uniform-complexity-tuples`
This fact is reflected in the abstraction:
~~~~ 
 eval_GetHashedPassPhrase_bb0_in(v_'filter_mode, v_'quietmode, v_'showpass, v_.noecho, v_16, v_25, v_27, v_3, v_40, v_45, v_46, v_noecho) -> Com_1(eval_GetHashedPassPhrase_bb1_in(v_'filter_mode, v_'quietmode, v_'showpass, 0, v_16, v_25, v_27, 0, v_40, v_45, v_46, v_noecho)) :|: v_'showpass < 0
  eval_GetHashedPassPhrase_bb0_in(v_'filter_mode, v_'quietmode, v_'showpass, v_.noecho, v_16, v_25, v_27, v_3, v_40, v_45, v_46, v_noecho) -> Com_1(eval_GetHashedPassPhrase_bb1_in(v_'filter_mode, v_'quietmode, v_'showpass, 0, v_16, v_25, v_27, 0, v_40, v_45, v_46, v_noecho)) :|: v_'showpass > 0
  eval_GetHashedPassPhrase_bb0_in(v_'filter_mode, v_'quietmode, v_'showpass, v_.noecho, v_16, v_25, v_27, v_3, v_40, v_45, v_46, v_noecho) -> Com_1(eval_GetHashedPassPhrase_bb1_in(v_'filter_mode, v_'quietmode, v_'showpass, v_noecho, v_16, v_25, v_27, v_noecho, v_40, v_45, v_46, v_noecho)) :|: v_'showpass = 0
~~~~

However, if I use the command:
`./llvm2kittel  buggy_example.bc -uniform-complexity-tuples -only-loop-conditions`
The generated file only contains:
~~~~
eval_GetHashedPassPhrase_bb0_in(v_'filter_mode, v_'quietmode, v_'showpass, v_.noecho, v_16, v_25, v_3, v_45, v_46, v_noecho) -> Com_1(eval_GetHashedPassPhrase_bb1_in(v_'filter_mode, v_'quietmode, v_'showpass, 0, v_16, v_25, 0, v_45, v_46, v_noecho))
~~~~
This is assigning noecho to 0 unconditionally which is incorrect.
I attach the source file (paswd.c function GetHashedPassPhrase), the llvm-ir file (buggy_example.bc) and the two generated abstractions (buggy_example.complete.koat and buggy_example.reduced.koat).
[bug_report.zip](https://github.com/s-falke/llvm2kittel/files/274278/bug_report.zip)

**Comment by s-falke** [comment]
Thanks for the detailed report this is indeed a bug, I'll push a fix momentarily.
